### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by BalestraPatrick**
I migrated the code to the stable version of Swift 3. 
Also migrated the tests and they all pass (both on iOS and on OS X). 👍

### CODE REVIEW

**Comment by matthewpalmer** [comment]
Looks good 👍. I've added you as a collaborator on the repo and registered you as an owner of the cocoapod (trying the Artsy model of more free access). Feel free to merge and release :)

Thanks very much!

**Comment by BalestraPatrick** [comment]
That sounds great, thanks! A few points that I would like to make clear before proceeding:
- Why is the file `AVAssetImageGeneratorTimePoints.swift` not in the project? I spent a while trying to figure out why Carthage wasn't building and it turns out that file is not included in the project and so the Xcode migrator didn't convert it to the last syntax. Can I insert it into the project to keep all the files in a single place?
- I was thinking to branch off the current master to keep a `swift2.3` branch. Then I could merge this PR into `master` that would support 3.0 by default in CocoaPods and Carthage. 

Let me know your thoughts about this process :)

**Comment by matthewpalmer** [comment]
Yeah I think so--no idea what's happened there. 

Sounds perfect 👌 

Thanks so much for your help!

**Comment by BalestraPatrick** [comment]
Nice! I just updated Travis to use Xcode 8 and the build passed at the first attempt 🎉
I also branched off [swift-2.3](https://github.com/matthewpalmer/Regift/tree/swift-2.3) for those still using it. I will soon try to release the pod. Do we release the current `master` and then people will be able to choose a specific branch for any Swift version?

**Comment by matthewpalmer** [comment]
Yep—release master as the latest and then people can use either the version
tags or the `:branch` specifier in their podfile.

Thanks again!

**Pull request merged**
